name: starter_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  cupertino_icons: ^1.0.8
  # dio: ^5.0.0
  easy_localization: ^3.0.0
  easy_sidemenu: ^0.7.1
  expansion_tile_group: ^2.3.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.0
  flutter_riverpod: ^2.0.0
  flutter_screenutil: ^5.9.3
  # flutter_side_menu: ^0.5.41
  getwidget: ^6.0.0
  go_router: ^7.0.0
  # logger: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.1.5
  # responsive_framework: ^0.2.0 
  # sqflite: ^2.0.0
  # supabase_flutter: ^2.9.1
  pluto_grid: ^8.0.0
  sqflite_common_ffi: ^2.3.4+4
  uuid: ^4.5.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translation/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
